version: "3"
services:
  app-server:
    container_name: 'spot_system'
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '8085:8085'
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/spots_system?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: user
    networks:
      - backend
    command: ["./wait-for-it.sh", "db:3306", "prod", "python", "app.py"]

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    expose:
      - '3306'
    environment:
      MYSQL_DATABASE: spots_system
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend

  prometheus:
    image: prom/prometheus:v2.19.3
    container_name: 'prometheus'
    volumes:
      - ./monitoring/prometheus:/etc/prometheus/
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command: "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - '9090:9090'
    expose:
      - '9090'
    networks:
      - backend

  grafana:
    image: grafana/grafana:7.1.0
    container_name: 'grafana'
    ports:
      - '3000:3000'
    volumes:
      - ./monitoring/grafana/provisioning/:/etc/grafana/provisioning/
    depends_on:
      - prometheus
    networks:
      - backend

volumes:
  db-data:
networks:
  backend: